### ISSUE TITLE
Rename Jumbotron component to HomeJumbotron

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi-javascript#44]
**Description**
This is part of a continuing effort to have more specific and consistent and predictable component names.

**TODO**
- [x] Rename Jumbotron component to HomeJumbotron
- [x] Move to components/fixtures
- [x] Fix any breaking references
