### ISSUE TITLE
Rename Carousel component to HomeEventsCarousel

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi-javascript#45]
**Description**
This is part of a continuing effort to have more specific and consistent and predictable component names.

**TODO**
- [x] Rename Carousel component to HomeEventsCarousel
- [x] Move to components/events
- [x] Fix any breaking references
