### ISSUE TITLE
Fill mock ticket component w/data with graphql mutation

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi-javascript#57]
**Description**
We need a visual/impactful way to demonstrate a basic ticket functionality. 

**PREREQUISITES**
Issue #40 needs to be completed before this issue can be worked on.

**TODO**
- [ ] create basic view button(next to each ticket in bought tickets list)
- [ ] onTouchTap of view button should open modal
- [ ] inside modal render ticket component
- [ ] fill ticket component with data from correct entry
