### ISSUE TITLE
remove relative imports from src/components

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi-javascript#62]
## Description
This pull requests is part of a series of issues for PR #58 and is a replacement for #52.

## Todo
- [x] Remove relative imports from buttons/LogoButton @kjg531
- [x] Remove relative imports from events/EventBox @kjg531
- [x] Remove relative imports from events/HomeEventsCarousel @kjg531
- [x] Remove relative imports from fixtures/HomeJumbotron @kjg531
- [x] Remove relative imports from Layout @kjg531
- [x] Remove relative imports from Link @kjg531
- [x] Remove relative imports from modal/AuthModal @kjg531
- [x] Remove relative imports from modal/AuthModal/SignInForm @kjg531
- [x] Remove relative imports from modal/SignupModal @kjg531
- [x] Remove relative imports from navigation/AccountNavigationMenu @kjg531
- [x] Remove relative imports from navigation/Auth @kjg531
- [x] Remove relative imports from navigation/Footer @kjg531
- [x] Remove relative imports from navigation/NavBarRightElement @kjg531
- [x] Remove relative imports from tickets/TicketPurchaseDialog @kjg531
- [x] Remove relative imports from tickets/TicketPurchaseListItem @kjg531
- [x] Remove relative imports from Html.js @kjg531
