### ISSUE TITLE
remove relative imports from src/routes

### ISSUE THREAD

**Issue by kjg531** [EventHi/EventHi-javascript#63]
## Description
This pull requests is part of a series of issues for PR #58 and is a replacement for #52.

## Todo
- [x] remove relative imports for about route @kjg531
- [x] remove relative imports for account route @kjg531
- [x] remove relative imports for browse route @kjg531
- [x] remove relative imports for contact route @kjg531
- [x] remove relative imports for create route @kjg531
- [x] remove relative imports for dashboard route @kjg531
- [x] remove relative imports for home route @kjg531
- [x] remove relative imports for notFound route @kjg531
- [x] remove relative imports for press route @kjg531
- [x] remove relative imports for pricing route @kjg531
- [x] remove relative imports for privacy route @kjg531
- [x] remove relative imports for security route @kjg531
- [x] remove relative imports for support route @kjg531
- [x] remove relative imports for terms route @kjg531
